### ISSUE TITLE
Crashed as soon as game open, on recent Testmod version from Steam.

### ISSUE THREAD

**Issue by Dylan-House** [280chan/TestMod#1]
Mod list:
 - basemod (5.46.1)
 - stslib (2.5.0)
 - RelicUpgradeLib (1.0.1)
 - testmod (5.11.2)

03:30:49.027 INFO core.CardCrawlGame> Exception occurred in CardCrawlGame create method!
03:30:49.030 ERROR core.CardCrawlGame> Exception caught
testmod.mymod.TestMod$1FileInconsistentException: Illegal modification to file "testmodResources/strings/relicStat.json" has been found.
	at testmod.mymod.TestMod.loadStats(TestMod.java:375) ~[testmod.jar:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_144]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_144]
	at testmod.mymod.TestMod.receiveEditStrings(TestMod.java:383) ~[testmod.jar:?]
	at basemod.BaseMod.publishEditStrings(BaseMod.java:2552) ~[?:?]
	at basemod.patches.com.megacrit.cardcrawl.localization.LocalizedStrings.EditStrings.Postfix(EditStrings.java:9) ~[?:?]
	at com.megacrit.cardcrawl.localization.LocalizedStrings.<init>(LocalizedStrings.java:228) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:260) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [?:?]
03:30:49.036 INFO basemod.BaseMod> publishPostInitialize

**Comment by 280chan** [comment]
I can open the game with exact same mods, it seems your mod file is corrupted, try unsubscribe and subscribe again

**Comment by 280chan** [comment]
Is the problem solved?

**Comment by Dylan-House** [comment]
took me a few times to resubscribe for the mod to work, looks like the problem is on my end, guess my network was unstable at times.

**Comment by 280chan** [comment]
Glad you figured it out.
